#!/bin/python

import sys

def solve(a0, a1, a2, b0, b1, b2):
    result = []
    result1 = []
    Alice = 0
    Bob = 0
    result.append(a0)
    result.append(a1)
    result.append(a2)
    result.append(b0)
    result.append(b1)
    result.append(b2)
    
    for i in range(3):
        if result[i] > result[i+3]:
            Alice += 1
        elif result[i] < result[i+3]:
            Bob += 1
        elif result[i] == result[i+3]:
            pass
    result1.append(Alice)
    result1.append(Bob)
    return result1
        
    # Complete this function

a0, a1, a2 = raw_input().strip().split(' ')
a0, a1, a2 = [int(a0), int(a1), int(a2)]
b0, b1, b2 = raw_input().strip().split(' ')
b0, b1, b2 = [int(b0), int(b1), int(b2)]
result = solve(a0, a1, a2, b0, b1, b2)
print " ".join(map(str, result))
